export const JAVA_TEMPLATE = [
  "Arrays.fill(dist, Integer.MAX_VALUE);",
  "PriorityQueue<Node> pq = new PriorityQueue<>(",
  "    Comparator.comparingInt(n -> n.cost));",
  "dist[start] = 0;",
  "pq.offer(new Node(start, 0));",
  "",
  "while (!pq.isEmpty()) {",
  "    Node cur = pq.poll();",
  "    if (cur.cost > dist[cur.node]) continue;",
  "",
  "    for (Edge edge : graph[cur.node]) {",
  "        int nextCost = cur.cost + edge.cost;",
  "        if (nextCost < dist[edge.to]) {",
  "            dist[edge.to] = nextCost;",
  "            pq.offer(new Node(edge.to, nextCost));",
  "        }",
  "    }",
  "}",
];
export const GRID_CODE = [
  "for (int[] row : dist) Arrays.fill(row, INF);",
  "dist[0][0] = 0;",
  "pq.offer(new Cell(0, 0, 0));",
  "",
  "while (!pq.isEmpty()) {",
  "    Cell cur = pq.poll();",
  "    if (cur.cost > dist[cur.r][cur.c]) continue;",
  "    for (int d = 0; d < 4; d++) {",
  "        int nr = cur.r + dr[d];",
  "        int nc = cur.c + dc[d];",
  "        if (nr < 0 || nr >= N || nc < 0 || nc >= N)",
  "            continue;",
  "        int nextCost = cur.cost + map[nr][nc];",
  "        if (nextCost < dist[nr][nc]) {",
  "            dist[nr][nc] = nextCost;",
  "            pq.offer(new Cell(nr, nc, nextCost));",
  "        }",
  "    }",
  "}",
];
export const javaFocus = [
  [0, 4],
  [7, 7],
  [8, 8],
  [10, 10],
  [11, 12],
  [13, 14],
];
export const gridFocus = [
  [0, 2],
  [5, 6],
  [7, 11],
  [12, 12],
  [13, 15],
];
export const javaNotes = [
  ["01", "초기화", "시작점은 0, 나머지는 ∞.", "시작 후보를 PQ에 넣는다."],
  ["02", "최소 후보 선택", "pq.poll()", "누적 비용이 가장 작은 후보를 꺼낸다."],
  [
    "03",
    "오래된 후보 제외",
    "cur.cost > dist[cur.node]",
    "이미 더 좋은 경로가 있으면 건너뛴다.",
  ],
  [
    "04",
    "인접 정점 확인",
    "graph[cur.node]",
    "현재 정점에서 나가는 간선을 확인한다.",
  ],
  [
    "05",
    "새 비용 계산·비교",
    "cur.cost + edge.cost",
    "기존 최소 비용보다 작은지 비교한다.",
  ],
  [
    "06",
    "갱신하고 PQ에 추가",
    "dist[edge.to] = nextCost",
    "더 싼 후보를 PQ에 다시 넣는다.",
  ],
];
export const gridNotes = [
  [
    "01",
    "시작점 초기화",
    "dist[0][0] = 0",
    "시작점에서 복구 비용 0으로 출발한다.",
  ],
  ["02", "최소 후보 선택", "pq.poll()", "오래된 후보는 건너뛴다."],
  ["03", "상하좌우 탐색", "(nr, nc)", "격자 범위를 벗어나는 좌표는 제외한다."],
  [
    "04",
    "도착할 칸의 비용",
    "cur.cost + map[nr][nc]",
    "현재 칸이 아니라 이동할 칸의 값을 더한다.",
  ],
  [
    "05",
    "최소 비용 갱신",
    "nextCost < dist[nr][nc]",
    "더 작으면 갱신하고 PQ에 추가한다.",
  ],
];
